In [ ]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
iris=load_iris()
x=iris.data
y=iris.target
df=pd.DataFrame(x,columns=iris.feature_names)
df['target']=y
print("sample of dataset:")
print(df.head())
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)
log_model=LogisticRegression(max_iter=200)
log_model.fit(x_train,y_train)
log_pred=log_model.predict(x_test)
nb_model=GaussianNB()
nb_model.fit(x_train,y_train)
nb_pred=nb_model.predict(x_test)
def evaluate_model(name,y_true,y_pred):
  print(f"\n{name} Evaluation:")
  print("Accuracy;",accuracy_score(y_true,y_pred))
  print("Confusion /matrix:\n",confusion_matrix(y_true,y_pred))
  print("Classification Report:\n",classification_report(y_true,y_pred))
evaluate_model("Logistic Regression",y_test,log_pred)
evaluate_model("Naive Bayes",y_test,nb_pred)



sample of dataset:
   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0  

Logistic Regression Evaluation:
Accuracy; 1.0
Confusion /matrix:
 [[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00        13

    accuracy                           1.00        45
   macro avg       1.00      1.00 